config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :borrowers
  get 'pages/about'

  get 'pages/contact'

  root 'borrowers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/borrower.rb
class Borrower < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  before_action :set_borrower, only: [:show, :edit, :update, :destroy]

  # GET /borrowers
  # GET /borrowers.json
  def index
    @borrowers = Borrower.all
  end

  # GET /borrowers/1
  # GET /borrowers/1.json
  def show
  end

  # GET /borrowers/new
  def new
    @borrower = Borrower.new
  end

  # GET /borrowers/1/edit
  def edit
  end

  # POST /borrowers
  # POST /borrowers.json
  def create
    @borrower = Borrower.new(borrower_params)

    respond_to do |format|
      if @borrower.save
        format.html { redirect_to @borrower, notice: 'Borrower was successfully created.' }
        format.json { render :show, status: :created, location: @borrower }
      else
        format.html { render :new }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowers/1
  # PATCH/PUT /borrowers/1.json
  def update
    respond_to do |format|
      if @borrower.update(borrower_params)
        format.html { redirect_to @borrower, notice: 'Borrower was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrower }
      else
        format.html { render :edit }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowers/1
  # DELETE /borrowers/1.json
  def destroy
    @borrower.destroy
    respond_to do |format|
      format.html { redirect_to borrowers_url, notice: 'Borrower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrower
      @borrower = Borrower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrower_params
      params.require(:borrower).permit(:name, :memo, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<h4>#{sentence}</h4>
			#{messages}
		</div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/borrowers/_form.html.erb
<%= form_for(borrower) do |f| %>
  <% if borrower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borrower.errors.count, "error") %> prohibited this borrower from being saved:</h2>

      <ul>
      <% borrower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :memo %>
      <%= f.text_area :memo, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit class:"btn btn-primary" %>
    </div>
<% end %>

app/views/borrowers/edit.html.erb
<h1>Editing Borrower</h1>

<%= render 'form', borrower: @borrower %>

<%= link_to 'Show', @borrower, class: "btn btn-link"  %> |
<%= link_to 'Back', borrowers_path, class: "btn btn-link" %>

app/views/borrowers/index.html.erb
<div class="center">
  <div class="row">
    <% @borrowers.each do |borrower| %>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-block">
              <h3 class="card-title"><%= borrower.name %></h3>
              <p class="card-text"><%= borrower.memo %></p>
              <h4><%= number_to_currency(borrower.price) %></h4>
              <span><%= link_to 'Show', borrower, class: "btn btn-secondary" %></span>
              <span><%= link_to 'Edit', edit_borrower_path(borrower), class: "btn btn-link" %></span>
              <span><%= link_to 'Destroy', borrower, method: :delete, data: { confirm: 'Are you sure?' },
                                class: "btn btn-secondary " %></span>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Borrower', new_borrower_path, class: "btn btn-link" %>

app/views/borrowers/new.html.erb
<h1>New Borrower</h1>

<%= render 'form', borrower: @borrower %>

<%= link_to 'Back', borrowers_path, class: "btn btn-link" %>

app/views/borrowers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="page-header">
    <h3><%= @borrower.name %></h3>
    <h4><%= @borrower.memo %><br>
      <div class="row">
        <div class="col-sm-8">
          <small><%= number_to_currency(@borrower.price) %></small>
        </div>
        <div class="col-sm-4">
          <%= link_to 'Edit', edit_borrower_path(@borrower), class: "btn btn-link" %> |
          <%= link_to 'Back', borrowers_path, class: "btn btn-link" %>
        </div>
      </div>
    </h4>
  </div>

</div>

app/views/layouts/_footer.html.erb
<p>Copyright 2017</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">GINRO-APP</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %> </li>
        <li><%= link_to "Contact", pages_contact_path %> </li>


      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
            <!-- Appear For the users who have already signed in -->
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
            <li><%= link_to "Edit Profile", edit_user_registration_path%> </li>

        <% else %>
            <!-- Appear below link for users who haven't signed in yet -->
            <li><%= link_to "Sign Up", new_user_registration_path %> </li>
            <li><%= link_to "Sign In", new_user_session_path%> </li>

        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/header' %>

  <div class="container">

    <!-- Devise Code which enables us to messages to users. For eg: Sign Successful-->
    <% flash.each do |name, msg| %>
        <if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        </if>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to Ginro</h1>
<h2>Ginro is an online service for Lending & Borrowing Money.</h2>

app/views/pages/contact.html.erb
<h1>Email us at CashApp.com</h1>